AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template para desplegar una función Lambda con API Gateway.

Parameters:
  LambdaCodeS3Bucket:
    Type: String
    Description: El nombre del bucket S3 donde está el código de la función Lambda.
  LambdaCodeS3Key:
    Type: String
    Description: La clave S3 del código de la función Lambda ZIP.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Runtime: python3.8

Outputs:
  LambdaFunctionName:
    Description: "Nombre de la función Lambda"
    Value: !Ref MyLambdaFunction

  ApiGatewayInvokeURL:
    Description: "Invoke URL del API Gateway"
    Value: !Sub "https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Stage/resource"